name: Pages

on:
  push:
    branches:
      - master  # default branch
    paths:
      - "benchmark/**"
      - ".github/workflows/pages.yml"
      - "package.json"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: ["native", "mhs", "koa", "express"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}          
      - name: Install Dependencies
        run: yarn install
      - name: Benchmark framework ${{ matrix.framework }}
        run: |
          mkdir -p /tmp/result/ /tmp/output/${{ matrix.framework }} /tmp/reporter
          node benchmark/frameworks/${{ matrix.framework }}.js
          PID=$!

          PWD=`pwd`
          docker run --name bench --rm --network=host \
          -v ${PWD}/benchmark/jmeter/http.jmx:/config/http.jmx \
          -v ${PWD}/benchmark/jmeter/entrypoint.sh:/entrypoint.sh \
          -v /tmp:/tmp \
          -e FRAMEWORK=${{ matrix.framework }} \
          yunnysunny/jmeter:latest
          kill $PID

  pages:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/reporter