name: Pages

on:
  push:
    branches:
      - master  # default branch
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'test/**'
env:
  NODE_ENV: production
  LOG_LEVEL: warn

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: ["native", "mhs", "koa", "express"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}          
      - name: Install Dependencies
        run: yarn install
      - name: Benchmark framework ${{ matrix.framework }}
        run: |
          mkdir -p /tmp/result/ /tmp/output/ /tmp/reporter/
          nohup node benchmark/frameworks/${{ matrix.framework }}.js  > nohup.log &

          PWD=`pwd`
          docker run --name bench --rm --network=host \
          -v ${PWD}/benchmark/jmeter/http.jmx:/config/http.jmx \
          -v ${PWD}/benchmark/jmeter/entrypoint.sh:/entrypoint.sh \
          -e FRAMEWORK=${{ matrix.framework }} \
          yunnysunny/jmeter:latest

      - name: Upload result of ${{ matrix.framework }}
        uses: actions/upload-artifact@v2
        with:
          name: result-${{ matrix.framework }}
          path: /tmp/reporter

  pages:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: result-native
          path: /tmp/reporter
      - uses: actions/download-artifact@v2
        with:
          name: result-mhs
          path: /tmp/reporter
      - uses: actions/download-artifact@v2
        with:
          name: result-koa
          path: /tmp/reporter
      - uses: actions/download-artifact@v2
        with:
          name: result-express
          path: /tmp/reporter
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/reporter