name: Pages

on:
  push:
    branches:
      - master  # default branch
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'test/**'
env:
  NODE_ENV: production
  LOG_LEVEL: warn
  GOMAXPROCS: 1

jobs:
  benchmark:
    runs-on: self-hosted
    strategy:
      matrix:        
        include:
          - framework: native
          - framework: mhs
          - framework: koa
          - framework: koa-router
            install-deps-separated: 1
          - framework: express
          - framework: nestjs
            install-deps-separated: 1
          - framework: fasthttp
            golang: 1
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Install Dependencies
        run: yarn install
      - name: Benchmark framework ${{ matrix.framework }}
        env: 
          INSTALL_DEPS_SEPARATED: ${{ matrix.install-deps-separated }}
          FRAMEWORK: ${{ matrix.framework }}
          BUILD_WITH_GOLANG: ${{ matrix.golang }}
        run: |
          mkdir -p /tmp/reporter/
          if [ "${INSTALL_DEPS_SEPARATED}" = "1" ] ; then
            make run-with-dep
          elif [ "${BUILD_WITH_GOLANG}" = "1" ] ; then
            make run-with-golang
          else
            make run-no-dep
          fi

          PWD=`pwd`
          docker run --name bench --rm --network=host \
          -v ${PWD}/benchmark/jmeter/http.jmx:/config/http.jmx \
          -v ${PWD}/benchmark/jmeter/entrypoint.sh:/entrypoint.sh \
          -v /tmp/reporter:/tmp/reporter \
          -e FRAMEWORK=${{ matrix.framework }} \
          yunnysunny/jmeter:latest

      - name: Upload result of ${{ matrix.framework }}
        uses: actions/upload-artifact@v2
        with:
          name: result-${{ matrix.framework }}
          path: /tmp/reporter/${{ matrix.framework }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/reporter
          allow_empty_commit: true
          keep_files: true

  # pages:
  #   needs: benchmark
  #   runs-on: self-hosted
  #   steps:
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: result-native
      #     path: /tmp/reporter/native
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: result-mhs
      #     path: /tmp/reporter/mhs
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: result-koa
      #     path: /tmp/reporter/koa
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: result-express
      #     path: /tmp/reporter/express
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: result-nestjs
      #     path: /tmp/reporter/nestjs
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: /tmp/reporter
      #     allow_empty_commit: true
